name: Run Postman Tests

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run Postman Collection
        run: postman collection run "48187952-217bd23e-f826-4f34-81b9-41fc6e253200" -e "48187952-948fbfd3-0fa7-4c62-9cde-12d8b83e8d17"
